AllCops:
  Exclude:
    - "**/Gemfile"
    - "**/Guardfile"
    - "**/Rakefile"
    - "bin/**/*"
    - "tmp/**/*"
  NewCops: "enable"
  RubyInterpreters:
    - "ruby"
  StyleGuideBaseURL: "https://rubystyle.guide"
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
